inherit_from:
  - .enabled.yml
  - .disabled.yml
#Style/StringLiterals:
#  EnforcedStyle: double_quotes
#  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:

      - 'app/helpers/**/*'
      - 'app/jobs/**/*'
      - 'app/mailers/**/*'
      - 'app/models/**/*'
      - 'app/notifiers/**'
      - 'app/services/products/research_products_service.rb'
      - 'app/services/mangopay/payin/module/flow_service.rb'
      - 'spec/mocks/*'
      - 'vendor/**/*'
      - 'test/**/*'
      - 'doc/**/*'
      - 'lib/**/*'
      - 'Gemfile'
      - 'bin/setup'
      - 'Capfile'
      - 'spec/controllers/**/*'
      - 'spec/features/**/*'
      - 'spec/models/**/*'
      - 'spec/i18n_spec.rb'
      - 'spec/payloads/**/*'
      - 'db/**/*'
      - 'config/**/*'
      - 'features/support/env.rb'
  DisabledByDefault: true
