development: &default
  adapter:  postgresql
  encoding: <%= ENV["DATABASE_ENCODING"] %>
  pool:     <%= ENV["DATABASE_POOL"] %>
  host:     <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: <%= ENV["DATABASE_NAME"] %>
  port:     <%= ENV["DATABASE_PORT"] %>
  timeout: 5000

test: &test
  <<: *default
  database: test_lcds_<%= ENV["USER"] %>_<%= ENV["TEST_ENV_NUMBER"] %>

staging:
  <<: *test

cucumber:
  <<: *test
